# Generated by Django 5.1.15 on 2026-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_check_in_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesetting',
            name='work_days',
            field=models.CharField(default='1,2,3,4,5', help_text='Comma-separated ISO weekday numbers treated as working days (1=Monday ... 7=Sunday). Drives which days require attendance and which days are eligible for a missed check-in request.', max_length=20),
        ),
    ]
