# Generated by Django 5.1.15 on 2026-09-27 06:46

import apps.attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesetting_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='work_days',
            field=models.CharField(default='1,2,3,4,5', help_text='Comma-separated ISO weekday numbers treated as working days (1=Monday ... 7=Sunday). Drives which days require attendance and which days are eligible for a missed check-in request.', max_length=20, validators=[apps.attendance.models.parse_work_days]),
        ),
    ]
