# Generated by Django 5.1.15 on 2026-09-27 08:54

import apps.attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_district_employee_division_employee_upazila_and_more'),
        ('attendance', '0005_alter_attendancesetting_work_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesetting',
            name='work_days',
            field=models.CharField(default='1,2,3,4,7', help_text='Comma-separated ISO weekday numbers treated as working days (1=Monday ... 7=Sunday). Drives which days require attendance and which days are eligible for a missed check-in request. Default is Sun-Thu (Friday and Saturday are weekly offs).', max_length=20, validators=[apps.attendance.models.parse_work_days]),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='ISO weekday number (1=Monday ... 7=Sunday)')),
                ('day_type', models.CharField(choices=[('G', 'General (Office)'), ('WH', 'Work from Home'), ('X', 'Weekly Off')], db_index=True, default='G', max_length=2)),
                ('start_time', models.TimeField(blank=True, help_text='Scheduled start time. Used for GENERAL days to compute the late cutoff.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Scheduled end time. Used to compute the OUT offset.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedules',
                'ordering': ['weekday'],
                'indexes': [models.Index(fields=['employee', 'weekday'], name='attendance__employe_9852c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'weekday'), name='unique_employee_schedule_weekday'), models.CheckConstraint(condition=models.Q(('weekday__gte', 1), ('weekday__lte', 7)), name='employee_schedule_weekday_range')],
            },
        ),
    ]
