# Generated by Django 5.1.15 on 2026-09-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('MANUAL_REQUEST_CREATED', 'Manual Request Created'), ('MANUAL_REQUEST_APPROVED', 'Manual Request Approved'), ('MANUAL_REQUEST_REJECTED', 'Manual Request Rejected'), ('ATTENDANCE_UPDATED', 'Attendance Updated'), ('USER_LOGIN', 'User Login'), ('USER_CREATED', 'User Created'), ('USER_DISABLED', 'User Disabled'), ('USER_ACTIVATED', 'User Activated'), ('USER_UPDATED', 'User Updated'), ('SETTING_UPDATED', 'Setting Updated'), ('SCHEDULE_UPDATE', 'Schedule Updated'), ('SCHEDULE_RESET', 'Schedule Reset')], db_index=True, max_length=60),
        ),
    ]
