# Generated by Django 5.1.15 on 2026-09-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualattendancerequest',
            name='request_type',
            field=models.CharField(choices=[('MISSED_CHECK_IN', 'Missed Check-In'), ('MISSED_CHECK_OUT', 'Missed Check-Out')], db_index=True, default='MISSED_CHECK_IN', help_text='MISSED_CHECK_IN: the assistant never checked in, so both times are supplied and the duty day is created. MISSED_CHECK_OUT: the assistant already checked in successfully and only the check-out is supplied; the existing server-recorded check-in is preserved untouched.', max_length=20),
        ),
        migrations.AlterField(
            model_name='manualattendancerequest',
            name='requested_check_in',
            field=models.DateTimeField(blank=True, help_text='Server-side check-in requested by the assistant. Null for MISSED_CHECK_OUT, where the existing automatic check-in is kept.', null=True),
        ),
    ]
